import kotlin.test.*

class ChessBoardTest {
    @Test
    fun testEmptyBoard() {
        val board = ChessBoard()
        assertEquals(
            """
                ........
                ........
                ........
                ........
                ........
                ........
                ........
                ........
            """.trimIndent(),
            board.toString()
        )
    }

    @Test
    fun testSimpleBoard() {
        val board = ChessBoard()
        board.array[0, 0] = ChessCell.Piece(ChessPieceKind.BISHOP, ChessPlayer.BLACK)
        board.array[1, 0] = ChessCell.Piece(ChessPieceKind.KNIGHT, ChessPlayer.WHITE)
        board.array[7, 6] = ChessCell.Piece(ChessPieceKind.KING, ChessPlayer.BLACK)
        assertEquals(
            """
                Bk......
                ........
                ........
                ........
                ........
                ........
                .......N
                ........
            """.trimIndent(),
            board.toString()
        )
    }

    @Test
    fun testDefaultBoard() {
        assertEquals(
            """
                RKBQNBKR
                PPPPPPPP
                ........
                ........
                ........
                ........
                pppppppp
                rkbqnbkr
            """.trimIndent(),
            ChessBoard.createDefault().toString()
        )
    }
}
